version: "3.7"
services:
    db:
        image: postgres:12-alpine
        container_name: tripsit_db
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
            - db_data:/docker-entrypoint-initdb.d
volumes:
    db_data:
        name: tripsit_db
        driver: local
